import type { Movie } from './types';

export const initialMovies: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., a dangerous task that requires a skilled team and a journey into the depths of the subconscious.',
    posterUrl: 'https://placehold.co/500x750/000000/FFFFFF.png',
    backdropUrl: 'https://placehold.co/1280x720/000000/FFFFFF.png',
    type: 'Movie',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 92,
    tags: ['Sci-Fi', 'Action', 'Thriller', 'Mind-bending'],
    releaseDate: 'Jul 16, 2010',
    director: 'Christopher Nolan',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Cobb', avatarUrl: 'https://placehold.co/100x100.png' },
      { name: 'Joseph Gordon-Levitt', character: 'Arthur', avatarUrl: 'https://placehold.co/100x100.png' },
      { name: 'Elliot Page', character: 'Ariadne', avatarUrl: 'https://placehold.co/100x100.png' },
      { name: 'Tom Hardy', character: 'Eames', avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    alternatePosters: [
      'https://placehold.co/500x750/111111/FFFFFF.png',
      'https://placehold.co/500x750/222222/FFFFFF.png',
      'https://placehold.co/500x750/333333/FFFFFF.png',
    ],
    rewatchCount: 3,
    scriptUrl: '#',
    collection: 'The Dark Knight Trilogy',
  },
  {
    id: '2',
    title: 'Attack on Titan',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    posterUrl: 'https://placehold.co/500x750/333333/FFFFFF.png',
    backdropUrl: 'https://placehold.co/1280x720/333333/FFFFFF.png',
    type: 'Anime',
    status: 'Watching',
    watchedEpisodes: 75,
    totalEpisodes: 88,
    rating: 95,
    tags: ['Anime', 'Dark Fantasy', 'Action', 'Post-apocalyptic'],
    releaseDate: 'Apr 7, 2013',
    director: 'Tetsurō Araki',
    cast: [
        { name: 'Yuki Kaji', character: 'Eren Yeager', avatarUrl: 'https://placehold.co/100x100.png' },
        { name: 'Yui Ishikawa', character: 'Mikasa Ackerman', avatarUrl: 'https://placehold.co/100x100.png' },
        { name: 'Marina Inoue', character: 'Armin Arlert', avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    rewatchCount: 1,
  },
  {
    id: '3',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    posterUrl: 'https://placehold.co/500x750/999999/FFFFFF.png',
    backdropUrl: 'https://placehold.co/1280x720/999999/FFFFFF.png',
    type: 'TV Show',
    status: 'Completed',
    watchedEpisodes: 62,
    totalEpisodes: 62,
    rating: 98,
    tags: ['Crime', 'Drama', 'Thriller', 'Neo-Western'],
    releaseDate: 'Jan 20, 2008',
    director: 'Vince Gilligan',
    cast: [
        { name: 'Bryan Cranston', character: 'Walter White', avatarUrl: 'https://placehold.co/100x100.png' },
        { name: 'Aaron Paul', character: 'Jesse Pinkman', avatarUrl: 'https://placehold.co/100x100.png' },
        { name: 'Anna Gunn', character: 'Skyler White', avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    rewatchCount: 2,
    collection: 'Breaking Bad Universe',
  },
  {
    id: '4',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    posterUrl: 'https://placehold.co/500x750/666666/FFFFFF.png',
    backdropUrl: 'https://placehold.co/1280x720/666666/FFFFFF.png',
    type: 'Anime',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 96,
    tags: ['Anime', 'Fantasy', 'Adventure', 'Coming-of-age'],
    releaseDate: 'Jul 20, 2001',
    director: 'Hayao Miyazaki',
    cast: [
        { name: 'Rumi Hiiragi', character: 'Chihiro', avatarUrl: 'https://placehold.co/100x100.png' },
        { name: 'Miyu Irino', character: 'Haku', avatarUrl: 'https://placehold.co/100x100.png' },
    ],
    alternatePosters: [
        'https://placehold.co/500x750/777777/FFFFFF.png',
        'https://placehold.co/500x750/888888/FFFFFF.png',
    ],
    rewatchCount: 5,
  },
  {
    id: '5',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://placehold.co/500x750/111111/FFFFFF.png',
    backdropUrl: 'https://placehold.co/1280x720/111111/FFFFFF.png',
    type: 'Movie',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 85,
    tags: ['Sci-Fi', 'Action', 'Cyberpunk'],
    releaseDate: 'Mar 31, 1999',
    director: 'The Wachowskis',
    rewatchCount: 4
  },
  {
    id: '6',
    title: 'Stranger Things',
    description: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    posterUrl: 'https://placehold.co/500x750/444444/FFFFFF.png',
    backdropUrl: 'https://placehold.co/1280x720/444444/FFFFFF.png',
    type: 'TV Show',
    status: 'On-Hold',
    watchedEpisodes: 34,
    totalEpisodes: 42,
    rating: 82,
    tags: ['Horror', 'Sci-Fi', '80s', 'Mystery'],
    releaseDate: 'Jul 15, 2016',
    rewatchCount: 0
  },
];
