import type { Movie } from './types';

export const initialMovies: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://placehold.co/500x750/000000/FFFFFF.png',
    type: 'Movie',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 5,
    tags: ['Sci-Fi', 'Action', 'Thriller', 'Mind-bending'],
  },
  {
    id: '2',
    title: 'Attack on Titan',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    posterUrl: 'https://placehold.co/500x750/333333/FFFFFF.png',
    type: 'Anime',
    status: 'Watching',
    watchedEpisodes: 75,
    totalEpisodes: 88,
    rating: 5,
    tags: ['Anime', 'Dark Fantasy', 'Action', 'Post-apocalyptic'],
  },
  {
    id: '3',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    posterUrl: 'https://placehold.co/500x750/999999/FFFFFF.png',
    type: 'Series',
    status: 'Completed',
    watchedEpisodes: 62,
    totalEpisodes: 62,
    rating: 5,
    tags: ['Crime', 'Drama', 'Thriller', 'Neo-Western'],
  },
  {
    id: '4',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    posterUrl: 'https://placehold.co/500x750/666666/FFFFFF.png',
    type: 'Anime',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 5,
    tags: ['Anime', 'Fantasy', 'Adventure', 'Coming-of-age'],
  },
  {
    id: '5',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://placehold.co/500x750/111111/FFFFFF.png',
    type: 'Movie',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 4,
    tags: ['Sci-Fi', 'Action', 'Cyberpunk'],
  },
  {
    id: '6',
    title: 'Stranger Things',
    description: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    posterUrl: 'https://placehold.co/500x750/444444/FFFFFF.png',
    type: 'Series',
    status: 'On-Hold',
    watchedEpisodes: 34,
    totalEpisodes: 42,
    rating: 4,
    tags: ['Horror', 'Sci-Fi', '80s', 'Mystery'],
  },
];
