import type { Movie } from './types';

export const initialMovies: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://placehold.co/500x750/000000/FFFFFF.png',
    type: 'Movie',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 92,
    tags: ['Sci-Fi', 'Action', 'Thriller', 'Mind-bending'],
    releaseDate: 'Jul 16, 2010',
  },
  {
    id: '2',
    title: 'Attack on Titan',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    posterUrl: 'https://placehold.co/500x750/333333/FFFFFF.png',
    type: 'Anime',
    status: 'Watching',
    watchedEpisodes: 75,
    totalEpisodes: 88,
    rating: 95,
    tags: ['Anime', 'Dark Fantasy', 'Action', 'Post-apocalyptic'],
    releaseDate: 'Apr 7, 2013',
  },
  {
    id: '3',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    posterUrl: 'https://placehold.co/500x750/999999/FFFFFF.png',
    type: 'TV Show',
    status: 'Completed',
    watchedEpisodes: 62,
    totalEpisodes: 62,
    rating: 98,
    tags: ['Crime', 'Drama', 'Thriller', 'Neo-Western'],
    releaseDate: 'Jan 20, 2008',
  },
  {
    id: '4',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    posterUrl: 'https://placehold.co/500x750/666666/FFFFFF.png',
    type: 'Anime',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 96,
    tags: ['Anime', 'Fantasy', 'Adventure', 'Coming-of-age'],
    releaseDate: 'Jul 20, 2001',
  },
  {
    id: '5',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://placehold.co/500x750/111111/FFFFFF.png',
    type: 'Movie',
    status: 'Completed',
    watchedEpisodes: 1,
    totalEpisodes: 1,
    rating: 85,
    tags: ['Sci-Fi', 'Action', 'Cyberpunk'],
    releaseDate: 'Mar 31, 1999',
  },
  {
    id: '6',
    title: 'Stranger Things',
    description: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    posterUrl: 'https://placehold.co/500x750/444444/FFFFFF.png',
    type: 'TV Show',
    status: 'On-Hold',
    watchedEpisodes: 34,
    totalEpisodes: 42,
    rating: 82,
    tags: ['Horror', 'Sci-Fi', '80s', 'Mystery'],
    releaseDate: 'Jul 15, 2016',
  },
];
